linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - prealloc
    - unconvert
    - gocritic
    - revive
    - bodyclose
    - goimports
    - whitespace
    - godot
    - errorlint

linters-settings:
  goimports:
    local-prefixes: github.com/woxQAQ/gim
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: error-strings
        severity: warning
  errorlint:
    errorf: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - bodyclose
    - path: mock.*\.go
      linters:
        - revive
        - errcheck
        - gosec
    - path: example.*\.go
      linters:
        - errcheck
        - gosec

run:
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 

