kafka_address:
  - 192.168.31.172:9092
topics:
  - SINGLE_MESSAGE_TRANSFER_TO_LOGIC
  - GROUP_MESSAGE_TRANSFER_TO_LOGIC
  - MESSAGE_ACK_LOGIC_TO_TRANSFER
  - SINGLE_PUSH_TO_TRANSFER
  - GROUP_PUSH_TO_TRANSFER
  - PUSH_ACK_TO_LOGIC
