kafka_address:
  - 192.168.31.172:9092
topics:
  - TRANSFER_SINGLE_MESSAGE_TO_LOGIC
  - TRANSFER_GROUP_MESSAGE_TO_LOGIC
  - LOGIC_MESSAGE_ACK_TO_TRANSFER
  - LOGIC_SINGLE_TO_TRANSFER
  - LOGIC_GROUP_TO_TRANSFER
  - TRANSFER_ACK_TO_LOGIC
